#!/bin/bash
# quick_examples.sh - Примеры использования инструментов

echo "📖 Bitcoin Wallet Tools - Примеры использования"
echo "=============================================="

# Активация окружения
source btc_env/bin/activate 2>/dev/null || echo "⚠️ Запустите из директории проекта"

echo ""
echo "🔧 WALLET_TOOL.PY - Индивидуальная генерация"
echo "--------------------------------------------"

echo ""
echo "1. Генерация 20 Segwit адресов для testnet:"
echo "python3 wallet_tool.py gen \\"
echo "  --network testnet \\"
echo "  --witness segwit \\"
echo "  --account 0 \\"
echo "  --count 20 \\"
echo "  --out-dir ./exports"

echo ""
echo "2. Генерация из мнемоники (замените на свою):"
echo "python3 wallet_tool.py gen \\"
echo "  --mnemonic \"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about\" \\"
echo "  --network bitcoin \\"
echo "  --witness segwit \\"
echo "  --count 10"

echo ""
echo "3. Верификация адресов из xpub:"
echo "python3 wallet_tool.py verify \\"
echo "  --xpub \"xpub6BosfCnifzxcFwrSzQiqu2DBVTshkCXacvNsWGYJVVhhawA7d4R5WSWGFNbi8Aw6ZRc1brxMyWMzG3DSSSSoekkudhUd9yLb6qx39T9nMdj\" \\"
echo "  --network bitcoin \\"
echo "  --witness segwit \\"
echo "  --start 0 \\"
echo "  --count 5"

echo ""
echo "🔧 MASS_WALLET_TOOL.PY - Массовая обработка"
echo "-------------------------------------------"

echo ""
echo "4. Массовая генерация адресов (матрица сетей):"
echo "python3 mass_wallet_tool.py gen-batch \\"
echo "  --matrix \"testnet:legacy,testnet:segwit,testnet:tr\" \\"
echo "  --accounts \"0-2\" \\"
echo "  --start 0 \\"
echo "  --count 50 \\"
echo "  --out-dir ./mass_exports \\"
echo "  --include-priv \\"
echo "  --save-mnemonic ./secure/test_mnemonic.txt"

echo ""
echo "5. Сканирование балансов (testnet):"
echo "python3 mass_wallet_tool.py scan \\"
echo "  --src-jsonl \"./mass_exports/addresses_*.jsonl\" \\"
echo "  --out-report ./scan_results.jsonl \\"
echo "  --workers 2 \\"
echo "  --delay-ms 200 \\"
echo "  --keystore-json ./mass_exports/keystore.json"

echo ""
echo "6. Сканирование с сохранением найденных ключей:"
echo "python3 mass_wallet_tool.py scan \\"
echo "  --src-jsonl \"./mass_exports/addresses_*.jsonl\" \\"
echo "  --out-report ./scan_results.jsonl \\"
echo "  --write-keys-on-hit \\"
echo "  --hits-dir ./hits \\"
echo "  --i-understand"

echo ""
echo "🔧 SHOW_HITS.PY - Просмотр результатов"
echo "--------------------------------------"

echo ""
echo "7. Просмотр найденных адресов с балансами:"
echo "python3 show_hits.py --report auto --min-sat 1"

echo ""
echo "8. Извлечение WIF ключа для адреса:"
echo "python3 show_hits.py \\"
echo "  --addr \"tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx\" \\"
echo "  --keystore keystore.jsonl \\"
echo "  --save-wif-to /mnt/c/Users/\$USER/Desktop/found_key.txt \\"
echo "  --print-wif"

echo ""
echo "9. Фильтрация результатов по сети и типу:"
echo "python3 show_hits.py \\"
echo "  --report scan_results.jsonl \\"
echo "  --network testnet \\"
echo "  --witness segwit \\"
echo "  --min-sat 1000"

echo ""
echo "🔧 BATCH_WALLETS.PY - Пакетная обработка"
echo "----------------------------------------"

echo ""
echo "10. Запуск пакетных заданий:"
echo "python3 batch_wallets.py \\"
echo "  --config example_batch_jobs.json \\"
echo "  --max-workers 4 \\"
echo "  --exports-dir ./batch_results"

echo ""
echo "📁 БЕЗОПАСНАЯ РАБОТА"
echo "-------------------"

echo ""
echo "11. Создание защищенной мнемоники:"
echo "python3 -c \"from bip_utils import Bip39MnemonicGenerator; print(Bip39MnemonicGenerator().FromWordsNumber(12))\" > ./secure/new_mnemonic.txt"
echo "chmod 600 ./secure/new_mnemonic.txt"

echo ""
echo "12. Резервное копирование результатов:"
echo "tar -czf backup_\$(date +%Y%m%d_%H%M%S).tar.gz exports/ mass_exports/ --exclude='*.log'"

echo ""
echo "🎯 БЫСТРЫЙ ТЕСТ"
echo "---------------"

echo ""
echo "13. Быстрый тест (5 testnet адресов):"
echo "python3 wallet_tool.py gen --network testnet --witness segwit --count 5"

echo ""
echo "💡 ПОЛЕЗНЫЕ АЛИАСЫ (после установки)"
echo "-----------------------------------"
echo "btc-activate  # Активация окружения"
echo "btc-gen --help       # Справка по wallet_tool.py"
echo "btc-mass --help      # Справка по mass_wallet_tool.py"
echo "btc-hits --help      # Справка по show_hits.py"
echo "btc-cd               # Переход в директорию проекта"

echo ""
echo "⚠️  ВАЖНО:"
echo "- Всегда используйте testnet для тестирования"
echo "- Храните мнемоники в папке ./secure/"
echo "- Проверяйте сгенерированные адреса перед использованием"
echo "- Используйте --i-understand только если понимаете риски"

echo ""
echo "🚀 Для начала запустите: python3 wallet_tool.py gen --network testnet --count 5"